name = "FLICameras"
uuid = "ed42ea77-59eb-4ccc-b6e7-572d949de904"
authors = ["Bossax <bossa.suan130@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
